listener:
  slotName: slot_1
  dump: false
  pubName: 
  ackTimeout: 10s
  refreshConnection: 30s
  heartbeatInterval: 10s

dumper:
  handler: 'esbulk' # defaults event, publisher is used. [event,esbulk,chddl,clickhouse]
  filesize: 0 # defaults 0: 1 MB(1*1024*1024), -1: no limit
  rows: 0 # defaults 0: 8164 rows, -1: no limit, 
  path: 
  repository:
    address: 'tcp://127.0.0.1:9000?dubug=true'
    host: 127.0.0.1
    port: 9000
    name: biz
    user:
    password:
    params:
      debug: true
    tables:
      table_name:
        engine: 
        engineParams:
        orderBy:
        partitionBy: 
        primaryKey: 
        sampleBy:
        settings:

logger:
  caller: false
  level: 'info' # defaults info, [warning,error,fatal,info,debug]
  humanReadable: true

database:
  host: 127.0.0.1
  port: 5432
  name: test
  user: pglogrepl
  password: secret
  filter:
    tables:
      table_name:
        - insert
        - update
        - delete

publisher:
  type: nats
  address: localhost:4222
  clusterID: test-cluster
  clientID: flow-client1
  topicPrefix: "pre"
