package database

const (
	SmallInt                 = "smallint"
	Integer                  = "integer"
	BigInt                   = "bigint"
	CharacterVarying         = "character varying"
	Varchar                  = "varchar"
	Text                     = "text"
	Real                     = "real"
	DoublePrecision          = "double precision"
	Timestamp                = "timestamp"
	TimestampWithTimeZone    = "timestamp with time zone"
	TimestampWithoutTimeZone = "timestamp without time zone"
	Date                     = "date"
	Time                     = "time"
	TimeWithoutTimeZone      = "time without time zone"
	TimeWithTimeZone         = "time with time zone"
	Interval                 = "interval"
	Boolean                  = "boolean"
	Decimal                  = "decimal"
	Numeric                  = "numeric"
	Character                = "character"
	Char                     = "char"
	JSONB                    = "jsonb"
	JSON                     = "json"
	UUID                     = "uuid"
	Bytea                    = "bytea"
	Inet                     = "inet"
)
